version: '3'

services:
  alb:
    image: nginx
    container_name: mkmk_alb
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/alb/default.conf:/etc/nginx/conf.d/default.conf:consistent
      - ./docker/alb/server.crt:/etc/nginx/ssl/server.crt:consistent
      - ./docker/alb/server.key:/etc/nginx/ssl/server.key:consistent
    networks:
      - common_link

  web:
    container_name: mkmk_web
    build: ./docker
    ports:
      - 8888:8888
    environment:
      CAKEPHP_ENV: development
    env_file:
      ./.env
    privileged: true
    volumes:
      - .:/var/www/html:cached
    networks:
      - common_link

  db:
    image: mysql:5.6
    container_name: mkmk_database_mysql
    ports:
      - 33060:3306
    networks:
      - common_link
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mkmk_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf.d/tanp.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d

networks:
  common_link:
    external: true
