<?php
declare(strict_types=1);

/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link      https://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   https://opensource.org/licenses/mit-license.php MIT License
 */
namespace App\Controller;

use App\Model\Domain\Slack\Client\SlackClient;
use Cake\Log\Log;

/**
 *
 */
class UsersController extends AppController
{
    /** @var SlackClient */
    private $slack_client;

    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->slack_client = new SlackClient();
    }

    public function index()
    {
        $this->autoRender = false;
        echo $this->slack_client->getAuthUrl("users:read");
    }

    public function login()
    {
        $code = $this->request->getQuery('code');

        if (empty($code)) {
            return $this->redirect($this->slack_client->getAuthUrl("users:read"));
        }

        $data = $this->slack_client->getAuthData($code);

        var_dump(json_encode($data->getJson()['authed_user']));
        var_dump(json_encode($data->getJson()));
    }
}
