<?php


namespace App\Model\Table;


use App\Model\Entity\User;

class AtsumarisUsersTable extends AppTable
{
    public function initialize(array $config): void
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
    }

}
