<?php


namespace App\Model\Table;


class MokmoksTable extends AppTable
{
    public function initialize(array $config): void
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
        $this->addBehavior('Timestamp');
    }
}
